#!/usr/bin/perl


#initialize the taps
$numStages= 0;
for($tap=0; $tap<100; ++$tap)
{
   $taps[$tap] = 0;
}

#read the taps from the command line
while ($tap = shift)
{
   $taps[$tap] = 1;
   if ($tap > $numStages)
   {
      $numStages = $tap;
   }
}
$codeLength = (1<<$numStages)-1;

if ($numStages == 0)
{
   &usage;
   exit(-1);
}

#initialize the stage delays to all ones
for($stageNum=1; $stageNum<=$numStages; ++$stageNum)
{
   $stage[$stageNum] = 1;
}

$tapString = "";
for($tap=$numStages; $tap>=1; --$tap)
{
   if ($taps[$tap] == 1) {$tapString .= "$tap ";};
}

$pnSequenceI = "";
$pnSequenceIQ = "";
$correlateRealCode = "";
$correlateImagCode = "";
#iternate over the pn sequence
for($iter=0; $iter<$codeLength; ++$iter)
{
   if ($stage[$numStages])
   {
      $outputI = "+1";
      $newline = <<END;
   _accReal[++index, index&=ACCUMULATOR_LENGTH_MASK] += real;
   _accImag[index] += imag;
END
      $correlate = $newline . $correlate;
   }
   else
   {
      $outputI = "-1";
      $newline = <<END;
   _accReal[++index, index&=ACCUMULATOR_LENGTH_MASK] -= real;
   _accImag[index] -= imag;
END
      $correlate = $newline . $correlate;
   }
   $newshift = 0;
   for($stageNum=$numStages; $stageNum>1; --$stageNum)
   {
      $newshift ^= ($taps[$stageNum] * $stage[$stageNum]);
      $stage[$stageNum] = $stage[$stageNum-1];
   }
   $stage[1] = $newshift;
   if ($iter%16 == 0) {$pnSequenceI .= "   ";}
   if ($iter%8 == 0) {$pnSequenceIQ .= "                           ";}
   $pnSequenceI .= $outputI;
   $pnSequenceIQ .= "\($outputI+0j\)";
   if ($iter < $codeLength-1) {$pnSequenceI .= ", ";}
   $pnSequenceIQ .= ",";
   if ($iter%16 == 15) {$pnSequenceI .= "\n";};
   if (($iter < $codeLength-1) &&($iter%8 == 7)) {$pnSequenceIQ .= "\n";};
}


####################################################################################
####################################################################################
#####                           Header Generation                              #####
####################################################################################
####################################################################################

open(HEADER, '>correlator_cc_impl.h');
open(CODE, '>correlator_cc_impl.cc');
open(TESTCODE, '>../python/qa_correlator_cc.py');



print HEADER <<END;
/* -*- c++ -*- */
/* 
 *
 * Convolve the input against a PN sequence to find the frame boundary.
 * 
 * <<< This file is autogenerated from pngen.pl.  Do not edit directly>>>
 *
 * This is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this software; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#ifndef INCLUDED_CORRELATOR_CC_CORRELATOR_CC_IMPL_H
#define INCLUDED_CORRELATOR_CC_CORRELATOR_CC_IMPL_H

#include <correlator_cc/correlator_cc.h>

#define CODE_LENGTH ($codeLength)
#define ACCUMULATOR_LENGTH (2048)
#define ACCUMULATOR_LENGTH_MASK (0x7ff)

namespace gr {
namespace correlator_cc {

class correlator_cc_impl : public correlator_cc
{

private:
   void detect_peak(long real, long imag);

   static const int _sequence[CODE_LENGTH];

   long _accReal[ACCUMULATOR_LENGTH];
   long _accImag[ACCUMULATOR_LENGTH];
   int _accIndex;  // Indexes the accumulator that is receiving its last contribution
   unsigned long _sampleNum;
   unsigned long _capsuleLen;

public:
   correlator_cc_impl();
   ~correlator_cc_impl();

   // Where all the action really happens
   void forecast (int noutput_items, gr_vector_int &ninput_items_required);

   int general_work(int noutput_items,
		    gr_vector_int &ninput_items,
		    gr_vector_const_void_star &input_items,
		    gr_vector_void_star &output_items);
}; // correlator_cc_impl

} // namespace correlator_cc
} // namespace gr

#endif /* INCLUDED_CORRELATOR_CC_CORRELATOR_CC_IMPL_H */
END

####################################################################################
####################################################################################
#####                            Code Generation                               #####
####################################################################################
####################################################################################

print CODE <<END;
/* -*- c++ -*- */
/* 
 * Convolve the input against a PN sequence to find the frame boundary.
 * 
 * <<< This file is autogenerated from pngen.pl.  Do not edit directly>>>
 * 
 * This is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this software; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <gr_io_signature.h>
#include <complex>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include "correlator_cc_impl.h"


namespace gr {
namespace correlator_cc {

//Taps: [ $tapString]
const int correlator_cc_impl::_sequence[$codeLength] = {
$pnSequenceI
};

static const int MIN_IN = 1;  // mininum number of input streams
static const int MAX_IN = 1;  // maximum number of input streams
static const int MIN_OUT = 1; // minimum number of output streams
static const int MAX_OUT = 1; // maximum number of output streams

correlator_cc::sptr
correlator_cc::make()
{
   return gnuradio::get_initial_sptr (new correlator_cc_impl());
}

/*
 * The private constructor
 */
correlator_cc_impl::correlator_cc_impl()
   : gr_block(
        "correlator_cc",
        gr_make_io_signature(MIN_IN, MAX_IN, sizeof(gr_complex)),
        gr_make_io_signature(MIN_OUT, MAX_OUT, sizeof(gr_complex)))
	
{
   int i;
   for (i=0; i<ACCUMULATOR_LENGTH; ++i)
   {
      _accReal[i] = 0;
      _accImag[i] = 0;
      _accIndex = 0;
   }
   _sampleNum = 0;
   _capsuleLen = 0;
}

/*
 * Our virtual destructor.
 */
correlator_cc_impl::~correlator_cc_impl()
{
}

void
correlator_cc_impl::detect_peak(long real, long imag)
{
   int index = _accIndex-1;
   double mag = sqrt(real*real + imag*imag);
   double scale = 65536 / mag;  // Normalize magnitude to 2^16

   // Normalization prevents weighting based on power.  While this may normally be desirable,
   // here it is not because it may weight the transmitter feedback incorrectly.
   // The result is more of a phase correlator.

   real = (long)(real*scale);
   imag = (long)(imag*scale);

$correlate

   ++_sampleNum;

   // Threshold the correlation
   double accReal = (double)_accReal[_accIndex];
   double accImag = (double)_accImag[_accIndex];
   if (sqrt(accReal*accReal + accImag*accImag) > 65536.0/2*CODE_LENGTH)
   {
      //printf("Peak on sample %ld\\n", _sampleNum);
      _capsuleLen = 10;  // TODO put this constant in a common header
   }

   ++_accIndex;
}


void
correlator_cc_impl::forecast (int noutput_items, gr_vector_int &ninput_items_required)
{
   ninput_items_required[0] = noutput_items;
}

int
correlator_cc_impl::general_work (
   int noutput_items,
   gr_vector_int &ninput_items,
   gr_vector_const_void_star &input_items,
   gr_vector_void_star &output_items
)
{
   const gr_complex* in = reinterpret_cast<const gr_complex*>(input_items[0]);
   gr_complex *out = reinterpret_cast<gr_complex*>(output_items[0]);
   int samplesRemaining = ninput_items[0];
   int samplesOutput = 0;
   int samplesRead = 0;

   while (samplesRemaining)
   {
      while (samplesRemaining && _capsuleLen)
      {
         // Peak has been detected, output this sample
	 // TODO: rotate

	 out[samplesOutput++] = in[samplesRead];
	 ++samplesRead;
	 --samplesRemaining;
	 --_capsuleLen;
      }

      while (samplesRemaining && !_capsuleLen)
      {
	 detect_peak(in[samplesRead].real(), in[samplesRead].imag());
	 ++samplesRead;
	 --samplesRemaining;
      }
   }

   // Tell runtime system how many input items we consumed on each input stream.
   consume_each (samplesRead);

   // Tell runtime system how many output items we produced.
   return samplesOutput;
}

} /* namespace correlator_cc */
} /* namespace gr */
END

####################################################################################
####################################################################################
#####                             Test Generation                              #####
####################################################################################
####################################################################################

print TESTCODE <<END;
#!/usr/bin/env python
# 
# Copyright 2013 <+YOU OR YOUR COMPANY+>.
# 
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this software; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street,
# Boston, MA 02110-1301, USA.
# 

from gnuradio import gr, gr_unittest
import correlator_cc_swig as correlator_cc

class qa_correlator_cc (gr_unittest.TestCase):

    def setUp (self):
        self.tb = gr.top_block ()

    def tearDown (self):
        self.tb = None

    def test_001_t (self):

        src_data        = (
			   # Random samples
			   (+1+1j),(+1-1j),(-1-1j),(-1+1j),(-1+1j),(+1-1j),(+1+1j),(-1-1j),(+1-1j),(+1+1j),
			   # PN Sequence
$pnSequenceIQ
			   # First frame data
			   (+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),
			   # Random samples
			   (+1+1j),(+1-1j),(-1-1j),(-1+1j),(-1+1j),(+1-1j),(+1+1j),(-1-1j),(+1-1j),(+1+1j),
			   # PN Sequence
$pnSequenceIQ
			   # Second frame data
			   (-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j))
        expected_data   = ((+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),(+1+0j),
			   (-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j),(-1+0j))
        source = gr.vector_source_c(src_data)
	dut = correlator_cc.correlator_cc()
        sink = gr.vector_sink_c()
        self.tb.connect(source, dut)
        self.tb.connect(dut, sink)
        self.tb.run()
        result_data = sink.data()
        #print expected_data
        #print result_data
        self.assertEqual(expected_data, result_data)


if __name__ == '__main__':
    gr_unittest.run(qa_correlator_cc, "qa_correlator_cc.xml")
END

close(TESTCODE);
close(CODE);
close(HEADER);


sub usage
{
   print <<END;
Usage: ./pngen.pl <tap>...
The number of taps must be non-zero.  
Number of stages is derived from the largest tap.

Maximal length taps are:
=========================
[ 2 1 ]
[ 3 2 ] [ 3 1 ]
[ 4 3 ] [ 4 1 ]
[ 5 3 ] [ 5 2 ]
[ 6 5 ] [ 6 1 ]
[ 7 6 ] [ 7 3 ] [ 7 1 ]
[ 8 6 5 4 ] [ 8 6 5 3 ]
[ 9 5 ] [ 9 6 4 3 ]
[ 10 7 ] [ 10 3 ]
[ 11 9 ] [ 11 8 5 2 ]
[ 12 6 4 1 ]
[ 13 4 3 1 ]
[ 14 5 3 1 ]
[ 15 14 ] [ 15 4 ]
[ 16 15 13 4 ]
[ 17 14 ] [ 17 3 ]
[ 18 11 ] [ 18 7 ]
[ 19 6 2 1 ]
[ 20 17 ] [ 20 3 ]
[ 21 19 ] [ 21 2 ]
[ 22 21 ] [ 22 1 ]
[ 23 18 ] [ 23 5 ]
[ 24 23 22 17 ]
[ 25 22 ] [ 25 3 ]
=========================
END
}
