/* -*- c++ -*- */
/* 
 * Copyright 2013 TRITONS
 *
 * <<<====================================================================>>>
 * <<<====================================================================>>>
 * <<< This file is autogenerated from walshgen.pl.  Do not edit directly >>>
 * <<<====================================================================>>>
 * <<<====================================================================>>>
 * 
 * This is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this software; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#ifndef INCLUDED_SPREADER_DESPREADER_CB_IMPL_H
#define INCLUDED_SPREADER_DESPREADER_CB_IMPL_H

#include <spreader/despreader_cb.h>

namespace gr {
namespace spreader {

class despreader_cb_impl : public despreader_cb
{
private:

public:
   despreader_cb_impl();
   ~despreader_cb_impl();

   void forecast (int noutput_items, gr_vector_int &ninput_items_required);

   // Where all the action really happens
   int general_work(int noutput_items,
      gr_vector_int &ninput_items,
      gr_vector_const_void_star &input_items,
      gr_vector_void_star &output_items);
};

} // namespace spreader
} // namespace gr

#endif /* INCLUDED_SPREADER_DESPREADER_CB_IMPL_H */

